# Managing my numpy experiments

In [3]:
import numpy as np

In [8]:
def main():
    x = np.array([0, 30, 60, 90, 120, 150])
    print("\nX = ",x)
    print("\nEnter values of Y seperated by a space : ")
    y = np.array(list(map(float, input().split())))
    print("\nY = ",y)
    
    harmonic=int(input("\nHow many harmonics do you require for your analysis: "))

    my_table = genreate_harmonic_analysis_table(x,y,harmonic)
    print_table(my_table)
    print_summations(my_table)

def r2d(num):
    return num*np.pi/180

In [23]:
x = np.array([0, 30, 60, 90, 120, 150])
y = np.array([1,2,3,4,5,6])

def genrate_harmonics(x,y,harmonic=3):
    tbl = np.ones((6,8), dtype='int32')
    
    tbl[:,0]=x
    tbl[:,1]=y

    tbl[:,2]=np.cos(tbl[:,0]*r2d(tbl[:,1]))
    print(tbl)

genrate_harmonics(x,y)

[[  0   1   1   1   1   1   1   1]
 [ 30   2   0   1   1   1   1   1]
 [ 60   3  -1   1   1   1   1   1]
 [ 90   4   1   1   1   1   1   1]
 [120   5   0   1   1   1   1   1]
 [150   6  -1   1   1   1   1   1]]
