# Managing my numpy experiments

In [2]:
import numpy as np

In [3]:
def main():
    x = np.array([0, 30, 60, 90, 120, 150])
    y = np.array([1,2,3,4,5,6])
    print("\nX = ",x)
    print("\nEnter values of Y seperated by a space : ")
    # y = np.array(list(map(float, input().split())))
    print("\nY = ",y)
    
    harmonic=int(input("\nHow many harmonics do you require for your analysis: "))

    my_table = genreate_harmonic_analysis_table(x,y,harmonic)
    print_table(my_table)
    print_summations(my_table)

def r2d(num):
    return num*np.pi/180

In [13]:
x = np.array([0, 30, 60, 90, 120, 150])
y = np.array([1,2,3,4,5,6])

def genreate_harmonic_analysis_table(x,y,harmonic=3):
    tbl = np.ones((6,2+2*harmonic), dtype='float32')
    
    tbl[:,0]=np.round(x,2)
    tbl[:,1]=np.round(y,2)

    for i in range(2*harmonic):
        if i<harmonic:
            temp = np.round(np.cos((i+1)*r2d(x)),2)
            temp=np.multiply(temp,tbl[:,1])
            tbl[:,i+2]=temp
        else:
            temp = np.round(np.sin((i-3)*r2d(x)),2)
            temp=np.multiply(temp,tbl[:,1])
            tbl[:,i+2]=temp
            
    return tbl

print(genreate_harmonic_analysis_table(x,y,harmonic=3))

[[  0.     1.     1.     1.     1.     0.     0.     0.  ]
 [ 30.     2.     1.74   1.     0.     0.     1.     1.74]
 [ 60.     3.     1.5   -1.5   -3.     0.     2.61   2.61]
 [ 90.     4.     0.    -4.    -0.     0.     4.     0.  ]
 [120.     5.    -2.5   -2.5    5.     0.     4.35  -4.35]
 [150.     6.    -5.22   3.     0.     0.     3.    -5.22]]


## Summations Of colums

In [14]:
def genrate_summations(tbl):
    sum_tbl=np.full(tbl.shape[1]-1,1)
    sum_tbl[0]=np.sum(tbl[:,1])

    for i in range(tbl.shape[1]-1):
        if i < tbl.shape[1]-1/2:
            sum_tbl[i+1]=np.sum(tbl[:,i+2])
    
    return sum_tbl

tbl = genreate_harmonic_analysis_table(x,y,4)

print(genrate_summations(tbl))

[21  1  1  1  1  1  1  1  1]
